default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["PGUSER"] || "postgres" %>
  password: 253789
  host:     <%= ENV["PGHOST"] || "localhost" %>
  port: <%= ENV["PGPORT"] || 5432 %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: little_eventbrite_development

test:
  <<: *default
  database: little_eventbrite_test

production:
  <<: *default
  database: little_eventbrite_production
  username: little_eventbrite
  password: <%= ENV["LITTLE_EVENTBRITE_DATABASE_PASSWORD"] %>